# Numpy

O numpy é uma biblioteca de algebra lienar para python, 


Os arrays do numpy são a parte mais importante do numpy

Os arrays vem ou e vetores ou em matrizes


Vetores são arrays de 1d
Matrizes são arrays em 2d(podem ter apenas uma coluna ou apenas uma linha)

---

## Array

Começamos criando uma lista normal no python,

`` my_list = [1,2,3] ``

Que armazena normalmente uma lista.

Agora, se importarmos a biblioteca numpy 

`` import numpy as np ``

Conseguimos trabalhar melhor a lista.

Podemos transformar a lista em um array por exemplo

``array = np.array(my_list) ``

e dessa forma, quando chamarmos a variavel array, ela vai retornar o seguinte 

`` array([1, 2, 3]) `` 

Um array, com um unico item, bidemensional.

Da mesma forma, conseguimos trabalhar com matrizes
Partindo de uma matriz simples, temos:

``my_matriz = [[1,2,3],[4,5,6],[7,8,8]]``

Dessa forma, quando passamos o conteudo pra função array do numpy, ele retorna um vetor tridimensional.

``np.array(my_matriz)``  que vai retornar

`` array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])``
       
Qual é a utilidade disso? até agora não entendi

---

### Arange()


O numpy tambem tem uma função similar com a ``range()`` do python

A função no numpy porem, trabalha com 3 argumentos.

``np.arange(0,10) ``


Quando executamos isso, o pytho retorna o seguinte:

``array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])``

Por que. A funçao arange, o primeiro argumento é ponto inicial, o pyhton começa com o index zero, então começamos no zero, e ele vai até o 10 mas não inclui, quando ele chega no 10 ele para de incrementar a lista, e o retorno é um **array**.
Na função arange, o terceiro argumento é o momento que o conteudo pula pro proximo, ou seja, se utilizarmos

``np.arange(0,11,2) ``


O pyhton vai retornar

``array([ 0,  2,  4,  6,  8, 10])``

Pq foi o momento que falamos pra ele pular para o proximo elemento

---
## Zeros()


De forma similar, temos a função zeros().

Ela cria um array contendo apenas zeros.

``np.zeros(3) `` 

Retorna

`` array([0., 0., 0.]) ``

Conseguimos porem, trabalhar em 3 dimensões aqui.
Utilizando a função zeros podemos gerar o seguinte

``np.zeros((3,4))``


A função aceita receber como parametro uma tupla, com as coordenadas da matriz que desejamos gerar, e por consequencia se chamamos a função, ela retorna 

``array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])``
       
 
---

## Ones()

Da mesma forma, o ones, alimenta um array com 1.

``np.ones(4)``

retorna 

``array([1., 1., 1., 1.])``

E se passarmos uma tupla com as coordenadas

``np.ones((5,5))``

O python retorna

``array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])``
       
---

## Linspace()

O linspace é similar com o ``arange()``  mas funciona diferente

Ele gera um array, **bidimensional**.

``np.linspace(0,5,4)``

A função recebe 3 parametros, o inicio, o fim e a quantidade de divisões que serão feitas do inicio até o elemento final, ou seja, o retorno da função acima vai ser 

``array([0.        , 1.66666667, 3.33333333, 5.        ])``

Um array, com 4 elementos, sendo o primeiro o elemento que foi dado como inicio, e o ultimo o elemento final.

---

## eye()

A função ``eye()`` gera uma matriz identidade, ou seja, a linha diagonal é composta por 1, e o resto dos elementos são zeros.

A função recebe um parametro unico, que é quantidade de elementos que a matriz vai ter, é só um elemento por ser uma matriz quadrada sempre.

``np.eye(5)`` 

Retorna o seguinte resultado

``array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])``
       
       
---
Vale dar uma olhada nas funções.
``np.random.<tab>``

## np.random.rand()

No numpy, existem varias formas de popular listas com numeros aleatorios entre 0 e 1.

``np.random.rand(4)``
    
    
Vai retornar algo similar com

``array([0.03016177, 0.09913604, 0.07849943, 0.02958948])``

A função pode gerar arrays de duas dimensões, só que, aqui ao inves do que foi feito anteriormente, só precisamos passar as coordenadas.

``np.random.rand(5,3)``

Vai retornar algo similar com

``array([[0.60906242, 0.96936401, 0.73594521],
       [0.00175455, 0.91728094, 0.47468791],
       [0.26374371, 0.97116156, 0.48839286],
       [0.62737613, 0.65366933, 0.78594883],
       [0.09566105, 0.84459024, 0.63480792]])``
       
Sabemos que é de duas dimensões apenas pelas duas chaves logo após os paranteses.

---

## np.random.randn()

Aqui, iremos gerar um array com numeros aleatorios baseados na distribuição gaussiana, eu não tenho nem ideia de como isso funciona

Quando chamamos a função

``np.random.randn(5)`` 

Retornamos algo similar com 

`` array([-0.80379066,  0.82267513, -0.25327063, -2.01766659, -1.37231566])``

A função tambem pode gerar uma matriz de 3 dimensões, mas não precisa ser passado uma tupla, apenas as coordenadas


``np.random.randn(4,3)``

Vai retornar algo similar com

``array([[ 1.40127254,  1.50152994,  0.32566803],
       [ 1.02160111,  1.34391654,  0.63664436],
       [-0.13289456, -0.46988342, -0.06743487],
       [-0.30368728, -1.162309  , -0.79853159]])``
       
       
---

## np.random.randint()

A função gera numero inteiros aleatorios, ela recebe 3 parametros, mas aceita se for passado apenas 2

``np.random.randint(1,100)``
 
 
Vai retornar um unico inteiro aleatorio, entre 1(inclusive) e 100(não inclusive)

``np.random.randint(1,100,10)``

Vai retornar uma lista de 10 numeros aleatorios, em um array, entre os numeros 1 e 100(não incluso), ficando com algo similar a 

``array([78, 61,  5, 73, 34, 65, 59,  7, 21, 56])``

---

In [19]:
my_list = [1,2,3]

In [2]:
my_list


[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
array1 = np.array(my_list)

In [6]:
array1

array([1, 2, 3])

In [7]:
my_matriz = [[1,2,3],[4,5,6],[7,8,8]]

In [8]:
np.array(my_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2) 

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(4)

array([0.03016177, 0.09913604, 0.07849943, 0.02958948])

In [31]:
np.random.rand(5,3)

array([[0.60906242, 0.96936401, 0.73594521],
       [0.00175455, 0.91728094, 0.47468791],
       [0.26374371, 0.97116156, 0.48839286],
       [0.62737613, 0.65366933, 0.78594883],
       [0.09566105, 0.84459024, 0.63480792]])

In [32]:
np.random.randn(5)

array([-0.80379066,  0.82267513, -0.25327063, -2.01766659, -1.37231566])

In [36]:
np.random.randn(4,3)

array([[ 1.40127254,  1.50152994,  0.32566803],
       [ 1.02160111,  1.34391654,  0.63664436],
       [-0.13289456, -0.46988342, -0.06743487],
       [-0.30368728, -1.162309  , -0.79853159]])

In [37]:
np.random.randint(1,100,10)

array([78, 61,  5, 73, 34, 65, 59,  7, 21, 56])

# Arrays

Vamo popular um array

`` arr = np.arange(25)``

Quando chamamos de volta a função, temos um array, de duas dimensões, populado pelos elementos 0 até o 24.

`` array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])``

de forma similar, podemos gerar 

``np.random.randint(0,50,10)``

Vai gerar um array, de inteiros, entre 0 e 50(não incluso) mas com 10 elementos

``array([12, 42,  2, 22,  3, 46, 43,  8, 49, 14])`` 

Agora, se queremos pegar o primeiro array, e transformar ele em tridimencional, podemos utilizar a função ``reshape``

## reshape()

A função ``reshape()`` remondula o array criado, ela recebe dois parametros, onde seriam as dimenções do array que vai ser retornado.
Quando rodamos 

``arr.reshape(5,5)``

O python retorna 

``array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])``
       
Que é um array de 3 dimensões, que contem os mesmos elementos que o array inicial.

**O python vai retornar um erro se ele não conseguir preencher a matriz completamente(para verificar podemos multiplicar os numeros passados na função reshape, o resultado tem que ser igual ao total de elementos do array)**

---

## .max() .min() .argmax() .argmin()

A função ``max()`` retorna o maior valor de um array

A função ``min()`` retorna o menor valor de um array

Ou seja,

``brr.max()`` 

Retorna ``49`` que é o maior elemento do array brr que foi criado anteriormente

``brr.min()``

Retorna ``2`` que é o menor elemento do array brr que foi criado anteriormente

---

A função ``.argmax()`` retorna a posição no array do maior valor

A função ``.argmin()`` retorna a posição no array do menor valor

Ou seja,

``brr.argmax()`` 

Retorna ``8`` que é o index do ``49`` que é o maior numero do array

``brr.argmin()``

Retorna ``2`` que é o index do ``2`` que é o menor numero do array

---

## shape

A função shape serve para descobrirmos a dimensão do array, o indice da matriz dele
 Por exemplo ``arr.shape`` Retorna ``(25,)`` ou seja, é bidimensional, e contem 25 elementos. Em outras palavras, é uma vertical unica, com 25 colunas
 
 Agora, quando utilizamos ``crr.shape`` Retornamos ``(5,5)`` que é as medidas que foram passadas quando realizamos o reshape do array ``arr``
 
 ---
 
 ## dtype
 
 A função retorna o tipo de dado que esta armazenado no array
 
 ``arr.dtype`` 
 
 Retorna
 
 ``dtype('int64')``
 
 que é o tipo de dado armazenado no array
 
 

In [51]:
arr = np.arange(25)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
brr = np.random.randint(0,50,10)

In [48]:
brr

array([12, 42,  2, 22,  3, 46, 43,  8, 49, 14])

In [47]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
brr.max()

49

In [50]:
brr.min()

2

In [52]:
brr

array([12, 42,  2, 22,  3, 46, 43,  8, 49, 14])

In [53]:
brr.argmax()

8

In [54]:
brr.argmin()

2

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
crr = arr.reshape(5,5)

In [57]:
crr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr.shape

(25,)

In [59]:
crr.shape

(5, 5)

In [60]:
arr.dtype

dtype('int64')