# Numpy

O numpy é uma biblioteca de algebra lienar para python, 


Os arrays do numpy são a parte mais importante do numpy

Os arrays vem ou e vetores ou em matrizes


Vetores são arrays de 1d
Matrizes são arrays em 2d(podem ter apenas uma coluna ou apenas uma linha)

---

## Array

Começamos criando uma lista normal no python,

`` my_list = [1,2,3] ``

Que armazena normalmente uma lista.

Agora, se importarmos a biblioteca numpy 

`` import numpy as np ``

Conseguimos trabalhar melhor a lista.

Podemos transformar a lista em um array por exemplo

``array = np.array(my_list) ``

e dessa forma, quando chamarmos a variavel array, ela vai retornar o seguinte 

`` array([1, 2, 3]) `` 

Um array, com um unico item, bidemensional.

Da mesma forma, conseguimos trabalhar com matrizes
Partindo de uma matriz simples, temos:

``my_matriz = [[1,2,3],[4,5,6],[7,8,8]]``

Dessa forma, quando passamos o conteudo pra função array do numpy, ele retorna um vetor tridimensional.

``np.array(my_matriz)``  que vai retornar

`` array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])``
       
Qual é a utilidade disso? até agora não entendi

---

### Arange()


O numpy tambem tem uma função similar com a ``range()`` do python

A função no numpy porem, trabalha com 3 argumentos.

``np.arange(0,10) ``


Quando executamos isso, o pytho retorna o seguinte:

``array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])``

Por que. A funçao arange, o primeiro argumento é ponto inicial, o pyhton começa com o index zero, então começamos no zero, e ele vai até o 10 mas não inclui, quando ele chega no 10 ele para de incrementar a lista, e o retorno é um **array**.
Na função arange, o terceiro argumento é o momento que o conteudo pula pro proximo, ou seja, se utilizarmos

``np.arange(0,11,2) ``


O pyhton vai retornar

``array([ 0,  2,  4,  6,  8, 10])``

Pq foi o momento que falamos pra ele pular para o proximo elemento

---
## Zeros()


De forma similar, temos a função zeros().

Ela cria um array contendo apenas zeros.

``np.zeros(3) `` 

Retorna

`` array([0., 0., 0.]) ``

Conseguimos porem, trabalhar em 3 dimensões aqui.
Utilizando a função zeros podemos gerar o seguinte

``np.zeros((3,4))``


A função aceita receber como parametro uma tupla, com as coordenadas da matriz que desejamos gerar, e por consequencia se chamamos a função, ela retorna 

``array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])``
       
 
---

## Ones()

Da mesma forma, o ones, alimenta um array com 1.

``np.ones(4)``

retorna 

``array([1., 1., 1., 1.])``

E se passarmos uma tupla com as coordenadas

``np.ones((5,5))``

O python retorna

``array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])``
       
---

## Linspace()

O linspace é similar com o ``arange()``  mas funciona diferente

Ele gera um array, **bidimensional**.

``np.linspace(0,5,4)``

A função recebe 3 parametros, o inicio, o fim e a quantidade de divisões que serão feitas do inicio até o elemento final, ou seja, o retorno da função acima vai ser 

``array([0.        , 1.66666667, 3.33333333, 5.        ])``

Um array, com 4 elementos, sendo o primeiro o elemento que foi dado como inicio, e o ultimo o elemento final.

---

## eye()

A função ``eye()`` gera uma matriz identidade, ou seja, a linha diagonal é composta por 1, e o resto dos elementos são zeros.

A função recebe um parametro unico, que é quantidade de elementos que a matriz vai ter, é só um elemento por ser uma matriz quadrada sempre.

``np.eye(5)`` 

Retorna o seguinte resultado

``array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])``
       
       
---
Vale dar uma olhada nas funções.
``np.random.<tab>``

## np.random.rand()

No numpy, existem varias formas de popular listas com numeros aleatorios entre 0 e 1.

``np.random.rand(4)``
    
    
Vai retornar algo similar com

``array([0.03016177, 0.09913604, 0.07849943, 0.02958948])``

A função pode gerar arrays de duas dimensões, só que, aqui ao inves do que foi feito anteriormente, só precisamos passar as coordenadas.

``np.random.rand(5,3)``

Vai retornar algo similar com

``array([[0.60906242, 0.96936401, 0.73594521],
       [0.00175455, 0.91728094, 0.47468791],
       [0.26374371, 0.97116156, 0.48839286],
       [0.62737613, 0.65366933, 0.78594883],
       [0.09566105, 0.84459024, 0.63480792]])``
       
Sabemos que é de duas dimensões apenas pelas duas chaves logo após os paranteses.

---

## np.random.randn()

Aqui, iremos gerar um array com numeros aleatorios baseados na distribuição gaussiana, eu não tenho nem ideia de como isso funciona

Quando chamamos a função

``np.random.randn(5)`` 

Retornamos algo similar com 

`` array([-0.80379066,  0.82267513, -0.25327063, -2.01766659, -1.37231566])``

A função tambem pode gerar uma matriz de 3 dimensões, mas não precisa ser passado uma tupla, apenas as coordenadas


``np.random.randn(4,3)``

Vai retornar algo similar com

``array([[ 1.40127254,  1.50152994,  0.32566803],
       [ 1.02160111,  1.34391654,  0.63664436],
       [-0.13289456, -0.46988342, -0.06743487],
       [-0.30368728, -1.162309  , -0.79853159]])``
       
       
---

## np.random.randint()

A função gera numero inteiros aleatorios, ela recebe 3 parametros, mas aceita se for passado apenas 2

``np.random.randint(1,100)``
 
 
Vai retornar um unico inteiro aleatorio, entre 1(inclusive) e 100(não inclusive)

``np.random.randint(1,100,10)``

Vai retornar uma lista de 10 numeros aleatorios, em um array, entre os numeros 1 e 100(não incluso), ficando com algo similar a 

``array([78, 61,  5, 73, 34, 65, 59,  7, 21, 56])``

---

In [2]:
my_list = [1,2,3]

In [3]:
my_list


[1, 2, 3]

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
array1 = np.array(my_list)

In [7]:
array1

array([1, 2, 3])

In [8]:
my_matriz = [[1,2,3],[4,5,6],[7,8,8]]

In [9]:
np.array(my_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2) 

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(4)

array([0.84543811, 0.64822519, 0.56713222, 0.31959381])

In [19]:
np.random.rand(5,3)

array([[0.98596715, 0.49939354, 0.8622818 ],
       [0.69950969, 0.26441058, 0.84946573],
       [0.09912608, 0.87324519, 0.08211009],
       [0.76044548, 0.40170746, 0.69644527],
       [0.68137199, 0.11183818, 0.55062405]])

In [20]:
np.random.randn(5)

array([ 1.72948513,  1.12193323, -0.09555576,  1.04853471, -0.53432663])

In [21]:
np.random.randn(4,3)

array([[-0.13511502, -0.0818218 , -0.86030351],
       [ 2.05696164, -1.09681778,  0.6616067 ],
       [-0.88340103,  0.05035442,  1.36908295],
       [-0.75677001, -1.19686356,  0.55621373]])

In [22]:
np.random.randint(1,100,10)

array([94, 38, 43, 24, 72, 44, 50, 60, 60, 62])

# Arrays

Vamo popular um array

`` arr = np.arange(25)``

Quando chamamos de volta a função, temos um array, de duas dimensões, populado pelos elementos 0 até o 24.

`` array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])``

de forma similar, podemos gerar 

``np.random.randint(0,50,10)``

Vai gerar um array, de inteiros, entre 0 e 50(não incluso) mas com 10 elementos

``array([12, 42,  2, 22,  3, 46, 43,  8, 49, 14])`` 

Agora, se queremos pegar o primeiro array, e transformar ele em tridimencional, podemos utilizar a função ``reshape``

## reshape()

A função ``reshape()`` remondula o array criado, ela recebe dois parametros, onde seriam as dimenções do array que vai ser retornado.
Quando rodamos 

``arr.reshape(5,5)``

O python retorna 

``array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])``
       
Que é um array de 3 dimensões, que contem os mesmos elementos que o array inicial.

**O python vai retornar um erro se ele não conseguir preencher a matriz completamente(para verificar podemos multiplicar os numeros passados na função reshape, o resultado tem que ser igual ao total de elementos do array)**

---

## .max() .min() .argmax() .argmin()

A função ``max()`` retorna o maior valor de um array

A função ``min()`` retorna o menor valor de um array

Ou seja,

``brr.max()`` 

Retorna ``49`` que é o maior elemento do array brr que foi criado anteriormente

``brr.min()``

Retorna ``2`` que é o menor elemento do array brr que foi criado anteriormente

---

A função ``.argmax()`` retorna a posição no array do maior valor

A função ``.argmin()`` retorna a posição no array do menor valor

Ou seja,

``brr.argmax()`` 

Retorna ``8`` que é o index do ``49`` que é o maior numero do array

``brr.argmin()``

Retorna ``2`` que é o index do ``2`` que é o menor numero do array

---

## shape

A função shape serve para descobrirmos a dimensão do array, o indice da matriz dele
 Por exemplo ``arr.shape`` Retorna ``(25,)`` ou seja, é bidimensional, e contem 25 elementos. Em outras palavras, é uma vertical unica, com 25 colunas
 
 Agora, quando utilizamos ``crr.shape`` Retornamos ``(5,5)`` que é as medidas que foram passadas quando realizamos o reshape do array ``arr``
 
 ---
 
 ## dtype
 
 A função retorna o tipo de dado que esta armazenado no array
 
 ``arr.dtype`` 
 
 Retorna
 
 ``dtype('int64')``
 
 que é o tipo de dado armazenado no array
 
 

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
brr = np.random.randint(0,50,10)

In [26]:
brr

array([36, 19, 13, 44, 20,  7,  0, 35,  6,  2])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
brr.max()

44

In [29]:
brr.min()

0

In [30]:
brr

array([36, 19, 13, 44, 20,  7,  0, 35,  6,  2])

In [31]:
brr.argmax()

3

In [32]:
brr.argmin()

6

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
crr = arr.reshape(5,5)

In [35]:
crr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(25,)

In [37]:
crr.shape

(5, 5)

In [38]:
arr.dtype

dtype('int64')

---
## Indexing e Selection

Trabalhando com index no array funciona normal.
Primeiro populamos o array

``` arr = np.arrange(0,11)```

Dessa forma quando chamamos a variavel arr ela retorna 

``` array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])```

Até o 10 pois não é inclusive.

Tendo o array populado, podemos trabalhar com as index dele.

Caso eu queira chamar o elemento no indice 8 ``` arr[8]```

Retornaremos 8 pois temos o numero 8 no indice 8.

Da mesma forma se quisermos pegar intervalos. ``` arr[3:8]```

Retorna ```array([3, 4, 5, 6, 7])``` 

Agora, se quisermos pegar de um ponto até o fim ou do inicio até um indice especifico, podemos trabalhar com o dois pontos``` arr[:5]```

Retorna desde o primeiro indice até o elemento que está no indice 4, o 5 não entra pois não é inclusive.

Da mesma forma, se quisermos ir pro fim do array ```arr[4:]```

Dessa forma teremos o array retornando do indice 4 até o ultimo elemento do array inclusive.

---

### Slice

Quando estamos trabalhando com arrays e queremos lidar só com um intervalo de um determinado array. por exemplo
Temos a variavel populada arr, partindo disso vamos popular uma variavle com um pedaço dessa.

```pedaco_arr = arr[2:5]``` 

Que quando chamada, vai retornar o elementos ```[2, 3, 4]```

Agora, se quiseremos fazer alteração nesses elementos, o array inicial vai sofrer as mudanças tambem. por exemplo

```pedaco_arr[:] = 88``` 

O que acontece aqui é o seguinte, pegamos a variavel ```pedaco_arr```  e por usarmos ```[:]``` vamos popular tudo o que tem dentro dela com 88, por mais que não saibamos quando index que ta ocupado ou não e essa alteração vai surtir efeito na variavel ```arr```. Agora, se chamarmos a variavel ```arr``` vai nos retornar ``` array([ 0,  1, 88, 88, 88,  5,  6,  7,  8,  9, 10])``` que é o resultado após as alterações feitas. Basicamente os dados não são copiados para um novo array, e sim funciona apenas como uma ```view```

---


In [39]:
import numpy as np

In [52]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [43]:
arr[:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [45]:
pedaco_arr = arr[2:5]

In [48]:
pedaco_arr

array([2, 3, 4])

In [49]:
pedaco_arr[:] = 88

In [50]:
pedaco_arr

array([88, 88, 88])

In [51]:
arr

array([ 0,  1, 88, 88, 88,  5,  6,  7,  8,  9, 10])

---
## Indexing em 2d

Quando trabalhamos com arrays em 2d e queremos indexar elementos especificos, podemos fazer de duas formas.

- Utilizandos duas chaves

- Utilizando virgulas.

Basicamente o metodo e o resultado é o mesmo.
Começamos populando um array 2d.

``` arr_2d = np.array([[5,10,15],[10,20,30],[15,30,45]]) ```

Caso queira pegar um elemento no primeira e terceira coluna podemos utilizar

```arr_2d[0,2] ``` ou ```arr_2d[0][2]``` que o resultado sera o mesmo

---

## Slide em 2d

Se quisermos pegar pedaços do array em 2d tb podemos.

por exemplo


```arr_2d[:2,1:] ```

Que vai pegar apenas as duas primeiras linhas e da primeira coluna em diante. Desta forma conseguimso filtrar os elementos que retornam, podendo ser apenas uma coluna, apenas um pedaço de uma linha, apenas um quadrante do array.

---
## Elementos Condicionais


```arr = np.array[1:10] ``` 

Podemos utilizar os elementos do array para fazer validações utilizando elementos de comparação. por exemplo

Partindo do array populado, podemos verificar qual dos elementos é maior que 5, nos retornara resultados booleanos.

```arr > 5 ```

```array([False, False, False, False, False,  True,  True,  True,  True,True])```
        
        
Conseguimos guardar o resultado em uma variavel.

```bool_arr = arr > 5 ```

Se quisermos ver os elementos numericos que retornam dessa consulta, podemos utilizar ```arr[bool_arr]```

que nos retornara um array apenas com os elementos que resultaram como ```True ``` anteriormente.

Para não utilizarmos duas etapas, podemos realizar a consulta direamente nas chaves: ```arr[arr > 5]```
Que o resultado vai ser o mesmo e economizamos um variavel.

In [75]:
arr_2d = np.array([[5,10,15],[10,20,30],[15,30,45]])

In [56]:
arr_2d

array([[ 5, 10, 15],
       [10, 20, 30],
       [15, 30, 45]])

In [57]:
arr_2d[0,2]

15

In [59]:
arr_2d[0][2]

15

In [60]:
arr_2d[:2,1:]

array([[10, 15],
       [20, 30]])

In [64]:
arr_2d[:,1:]

array([[10, 15],
       [20, 30],
       [30, 45]])

In [71]:
arr = np.arange(1,11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [76]:
bool_arr = arr > 5 

In [77]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [79]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [80]:
arr_2d = np.arange(50).reshape(5,10)

In [82]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])